<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\City;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cityRecords = [
            ['id' => 1, 'name' => 'Cuenca', 'state_id' => 1],
            ['id' => 2, 'name' => 'Girón', 'state_id' => 1],
            ['id' => 3, 'name' => 'Gualaceo', 'state_id' => 1],
            ['id' => 4, 'name' => 'Nabón', 'state_id' => 1],
            ['id' => 5, 'name' => 'Paute', 'state_id' => 1],
            ['id' => 6, 'name' => 'Pucara', 'state_id' => 1],
            ['id' => 7, 'name' => 'San Fernando', 'state_id' => 1],
            ['id' => 8, 'name' => 'Santa Isabel', 'state_id' => 1],
            ['id' => 9, 'name' => 'Sigsig', 'state_id' => 1],
            ['id' => 10, 'name' => 'Oña', 'state_id' => 1],
            ['id' => 11, 'name' => 'Chordeleg', 'state_id' => 1],
            ['id' => 12, 'name' => 'El Pan', 'state_id' => 1],
            ['id' => 13, 'name' => 'Sevilla de Oro', 'state_id' => 1],
            ['id' => 14, 'name' => 'Guachapala', 'state_id' => 1],
            ['id' => 15, 'name' => 'Camilo Ponce Enríquez', 'state_id' => 1],
            ['id' => 16, 'name' => 'Guaranda', 'state_id' => 2],
            ['id' => 17, 'name' => 'Chillanes', 'state_id' => 2],
            ['id' => 18, 'name' => 'Chimbo', 'state_id' => 2],
            ['id' => 19, 'name' => 'Echeandía', 'state_id' => 2],
            ['id' => 20, 'name' => 'San Miguel', 'state_id' => 2],
            ['id' => 21, 'name' => 'Caluma', 'state_id' => 2],
            ['id' => 22, 'name' => 'Las Naves', 'state_id' => 2],
            ['id' => 23, 'name' => 'Azogues', 'state_id' => 3],
            ['id' => 24, 'name' => 'Biblián', 'state_id' => 3],
            ['id' => 25, 'name' => 'Cañar', 'state_id' => 3],
            ['id' => 26, 'name' => 'La Troncal', 'state_id' => 3],
            ['id' => 27, 'name' => 'El Tambo', 'state_id' => 3],
            ['id' => 28, 'name' => 'Déleg', 'state_id' => 3],
            ['id' => 29, 'name' => 'Suscal', 'state_id' => 3],
            ['id' => 30, 'name' => 'Tulcán', 'state_id' => 4],
            ['id' => 31, 'name' => 'Bolívar', 'state_id' => 4],
            ['id' => 32, 'name' => 'Espejo', 'state_id' => 4],
            ['id' => 33, 'name' => 'Mira', 'state_id' => 4],
            ['id' => 34, 'name' => 'Montúfar', 'state_id' => 4],
            ['id' => 35, 'name' => 'San Pedro de Huaca', 'state_id' => 4],
            ['id' => 36, 'name' => 'Latacunga', 'state_id' => 5],
            ['id' => 37, 'name' => 'La Maná', 'state_id' => 5],
            ['id' => 38, 'name' => 'Pangua', 'state_id' => 5],
            ['id' => 39, 'name' => 'Pujili', 'state_id' => 5],
            ['id' => 40, 'name' => 'Salcedo', 'state_id' => 5],
            ['id' => 41, 'name' => 'Saquisilí', 'state_id' => 5],
            ['id' => 42, 'name' => 'Sigchos', 'state_id' => 5],
            ['id' => 43, 'name' => 'Riobamba', 'state_id' => 6],
            ['id' => 44, 'name' => 'Alausi', 'state_id' => 6],
            ['id' => 45, 'name' => 'Colta', 'state_id' => 6],
            ['id' => 46, 'name' => 'Chambo', 'state_id' => 6],
            ['id' => 47, 'name' => 'Chunchi', 'state_id' => 6],
            ['id' => 48, 'name' => 'Guamote', 'state_id' => 6],
            ['id' => 49, 'name' => 'Guano', 'state_id' => 6],
            ['id' => 50, 'name' => 'Pallatanga', 'state_id' => 6],
            ['id' => 51, 'name' => 'Penipe', 'state_id' => 6],
            ['id' => 52, 'name' => 'Cumandá', 'state_id' => 6],
            ['id' => 53, 'name' => 'Machala', 'state_id' => 7],
            ['id' => 54, 'name' => 'Arenillas', 'state_id' => 7],
            ['id' => 55, 'name' => 'Atahualpa', 'state_id' => 7],
            ['id' => 56, 'name' => 'Balsas', 'state_id' => 7],
            ['id' => 57, 'name' => 'Chilla', 'state_id' => 7],
            ['id' => 58, 'name' => 'El Guabo', 'state_id' => 7],
            ['id' => 59, 'name' => 'Huaquillas', 'state_id' => 7],
            ['id' => 60, 'name' => 'Marcabelí', 'state_id' => 7],
            ['id' => 61, 'name' => 'Pasaje', 'state_id' => 7],
            ['id' => 62, 'name' => 'Piñas', 'state_id' => 7],
            ['id' => 63, 'name' => 'Portovelo', 'state_id' => 7],
            ['id' => 64, 'name' => 'Santa Rosa', 'state_id' => 7],
            ['id' => 65, 'name' => 'Zaruma', 'state_id' => 7],
            ['id' => 66, 'name' => 'Las Lajas', 'state_id' => 7],
            ['id' => 67, 'name' => 'Esmeraldas', 'state_id' => 8],
            ['id' => 68, 'name' => 'Eloy Alfaro', 'state_id' => 8],
            ['id' => 69, 'name' => 'Muisne', 'state_id' => 8],
            ['id' => 70, 'name' => 'Quinindé', 'state_id' => 8],
            ['id' => 71, 'name' => 'San Lorenzo', 'state_id' => 8],
            ['id' => 72, 'name' => 'Atacames', 'state_id' => 8],
            ['id' => 73, 'name' => 'Rioverde', 'state_id' => 8],
            ['id' => 74, 'name' => 'La Concordia', 'state_id' => 8],
            ['id' => 75, 'name' => 'Guayaquil', 'state_id' => 9],
            ['id' => 76, 'name' => 'Alfredo Baquerizo Moreno (Juján)', 'state_id' => 9],
            ['id' => 77, 'name' => 'Balao', 'state_id' => 9],
            ['id' => 78, 'name' => 'Balzar', 'state_id' => 9],
            ['id' => 79, 'name' => 'Colimes', 'state_id' => 9],
            ['id' => 80, 'name' => 'Daule', 'state_id' => 9],
            ['id' => 81, 'name' => 'Durán', 'state_id' => 9],
            ['id' => 82, 'name' => 'El Empalme', 'state_id' => 9],
            ['id' => 83, 'name' => 'El Triunfo', 'state_id' => 9],
            ['id' => 84, 'name' => 'Milagro', 'state_id' => 9],
            ['id' => 85, 'name' => 'Naranjal', 'state_id' => 9],
            ['id' => 86, 'name' => 'Naranjito', 'state_id' => 9],
            ['id' => 87, 'name' => 'Palestina', 'state_id' => 9],
            ['id' => 88, 'name' => 'Pedro Carbo', 'state_id' => 9],
            ['id' => 89, 'name' => 'Samborondón', 'state_id' => 9],
            ['id' => 90, 'name' => 'Santa Lucía', 'state_id' => 9],
            ['id' => 91, 'name' => 'Salitre', 'state_id' => 9],
            ['id' => 92, 'name' => 'San Jacinto de Yaguachi', 'state_id' => 9],
            ['id' => 93, 'name' => 'Playas', 'state_id' => 9],
            ['id' => 94, 'name' => 'Simón Bolívar', 'state_id' => 9],
            ['id' => 95, 'name' => 'Coronel Marcelino Maridueña', 'state_id' => 9],
            ['id' => 96, 'name' => 'Lomas de Sargentillo', 'state_id' => 9],
            ['id' => 97, 'name' => 'Nobol', 'state_id' => 9],
            ['id' => 98, 'name' => 'General Antonio Elizalde', 'state_id' => 9],
            ['id' => 99, 'name' => 'Isidro Ayora', 'state_id' => 9],
            ['id' => 100, 'name' => 'Ibarra', 'state_id' => 10],
            ['id' => 101, 'name' => 'Antonio Ante', 'state_id' => 10],
            ['id' => 102, 'name' => 'Cotacachi', 'state_id' => 10],
            ['id' => 103, 'name' => 'Otavalo', 'state_id' => 10],
            ['id' => 104, 'name' => 'Pimampiro', 'state_id' => 10],
            ['id' => 105, 'name' => 'San Miguel de Urcuquí', 'state_id' => 10],
            ['id' => 106, 'name' => 'Loja', 'state_id' => 11],
            ['id' => 107, 'name' => 'Calvas', 'state_id' => 11],
            ['id' => 108, 'name' => 'Catamayo', 'state_id' => 11],
            ['id' => 109, 'name' => 'Celica', 'state_id' => 11],
            ['id' => 110, 'name' => 'Chaguarpamba', 'state_id' => 11],
            ['id' => 111, 'name' => 'Espíndola', 'state_id' => 11],
            ['id' => 112, 'name' => 'Gonzanamá', 'state_id' => 11],
            ['id' => 113, 'name' => 'Macará', 'state_id' => 11],
            ['id' => 114, 'name' => 'Paltas', 'state_id' => 11],
            ['id' => 115, 'name' => 'Puyango', 'state_id' => 11],
            ['id' => 116, 'name' => 'Saraguro', 'state_id' => 11],
            ['id' => 117, 'name' => 'Sozoranga', 'state_id' => 11],
            ['id' => 118, 'name' => 'Zapotillo', 'state_id' => 11],
            ['id' => 119, 'name' => 'Pindal', 'state_id' => 11],
            ['id' => 120, 'name' => 'Quilanga', 'state_id' => 11],
            ['id' => 121, 'name' => 'Olmedo', 'state_id' => 11],
            ['id' => 122, 'name' => 'Babahoyo', 'state_id' => 12],
            ['id' => 123, 'name' => 'Baba', 'state_id' => 12],
            ['id' => 124, 'name' => 'Montalvo', 'state_id' => 12],
            ['id' => 125, 'name' => 'Puebloviejo', 'state_id' => 12],
            ['id' => 126, 'name' => 'Quevedo', 'state_id' => 12],
            ['id' => 127, 'name' => 'Urdaneta', 'state_id' => 12],
            ['id' => 128, 'name' => 'Ventanas', 'state_id' => 12],
            ['id' => 129, 'name' => 'Vínces', 'state_id' => 12],
            ['id' => 130, 'name' => 'Palenque', 'state_id' => 12],
            ['id' => 131, 'name' => 'Buena Fé', 'state_id' => 12],
            ['id' => 132, 'name' => 'Valencia', 'state_id' => 12],
            ['id' => 133, 'name' => 'Mocache', 'state_id' => 12],
            ['id' => 134, 'name' => 'Quinsaloma', 'state_id' => 12],
            ['id' => 135, 'name' => 'Portoviejo', 'state_id' => 13],
            ['id' => 136, 'name' => 'Bolívar', 'state_id' => 13],
            ['id' => 137, 'name' => 'Chone', 'state_id' => 13],
            ['id' => 138, 'name' => 'El Carmen', 'state_id' => 13],
            ['id' => 139, 'name' => 'Flavio Alfaro', 'state_id' => 13],
            ['id' => 140, 'name' => 'Jipijapa', 'state_id' => 13],
            ['id' => 141, 'name' => 'Junín', 'state_id' => 13],
            ['id' => 142, 'name' => 'Manta', 'state_id' => 13],
            ['id' => 143, 'name' => 'Montecristi', 'state_id' => 13],
            ['id' => 144, 'name' => 'Paján', 'state_id' => 13],
            ['id' => 145, 'name' => 'Pichincha', 'state_id' => 13],
            ['id' => 146, 'name' => 'Rocafuerte', 'state_id' => 13],
            ['id' => 147, 'name' => 'Santa Ana', 'state_id' => 13],
            ['id' => 148, 'name' => 'Sucre', 'state_id' => 13],
            ['id' => 149, 'name' => 'Tosagua', 'state_id' => 13],
            ['id' => 150, 'name' => '24 de Mayo', 'state_id' => 13],
            ['id' => 151, 'name' => 'Pedernales', 'state_id' => 13],
            ['id' => 152, 'name' => 'Olmedo', 'state_id' => 13],
            ['id' => 153, 'name' => 'Puerto López', 'state_id' => 13],
            ['id' => 154, 'name' => 'Jama', 'state_id' => 13],
            ['id' => 155, 'name' => 'Jaramijó', 'state_id' => 13],
            ['id' => 156, 'name' => 'San Vicente', 'state_id' => 13],
            ['id' => 157, 'name' => 'Morona', 'state_id' => 14],
            ['id' => 158, 'name' => 'Gualaquiza', 'state_id' => 14],
            ['id' => 159, 'name' => 'Limón Indanza', 'state_id' => 14],
            ['id' => 160, 'name' => 'Palora', 'state_id' => 14],
            ['id' => 161, 'name' => 'Santiago', 'state_id' => 14],
            ['id' => 162, 'name' => 'Sucúa', 'state_id' => 14],
            ['id' => 163, 'name' => 'Huamboya', 'state_id' => 14],
            ['id' => 164, 'name' => 'San Juan Bosco', 'state_id' => 14],
            ['id' => 165, 'name' => 'Taisha', 'state_id' => 14],
            ['id' => 166, 'name' => 'Logroño', 'state_id' => 14],
            ['id' => 167, 'name' => 'Pablo Sexto', 'state_id' => 14],
            ['id' => 168, 'name' => 'Tiwintza', 'state_id' => 14],
            ['id' => 169, 'name' => 'Tena', 'state_id' => 15],
            ['id' => 170, 'name' => 'Archidona', 'state_id' => 15],
            ['id' => 171, 'name' => 'El Chaco', 'state_id' => 15],
            ['id' => 172, 'name' => 'Quijos', 'state_id' => 15],
            ['id' => 173, 'name' => 'Carlos Julio Arosemena Tola', 'state_id' => 15],
            ['id' => 174, 'name' => 'Pastaza', 'state_id' => 16],
            ['id' => 175, 'name' => 'Mera', 'state_id' => 16],
            ['id' => 176, 'name' => 'Santa Clara', 'state_id' => 16],
            ['id' => 177, 'name' => 'Arajuno', 'state_id' => 16],
            ['id' => 178, 'name' => 'Quito', 'state_id' => 17],
            ['id' => 179, 'name' => 'Cayambe', 'state_id' => 17],
            ['id' => 180, 'name' => 'Mejia', 'state_id' => 17],
            ['id' => 181, 'name' => 'Pedro Moncayo', 'state_id' => 17],
            ['id' => 182, 'name' => 'Rumiñahui', 'state_id' => 17],
            ['id' => 183, 'name' => 'San Miguel de Los Bancos', 'state_id' => 17],
            ['id' => 184, 'name' => 'Pedro Vicente Maldonado', 'state_id' => 17],
            ['id' => 185, 'name' => 'Puerto Quito', 'state_id' => 17],
            ['id' => 186, 'name' => 'Ambato', 'state_id' => 18],
            ['id' => 187, 'name' => 'Baños de Agua Santa', 'state_id' => 18],
            ['id' => 188, 'name' => 'Cevallos', 'state_id' => 18],
            ['id' => 189, 'name' => 'Mocha', 'state_id' => 18],
            ['id' => 190, 'name' => 'Patate', 'state_id' => 18],
            ['id' => 191, 'name' => 'Quero', 'state_id' => 18],
            ['id' => 192, 'name' => 'San Pedro de Pelileo', 'state_id' => 18],
            ['id' => 193, 'name' => 'Santiago de Píllaro', 'state_id' => 18],
            ['id' => 194, 'name' => 'Tisaleo', 'state_id' => 18],
            ['id' => 195, 'name' => 'Zamora', 'state_id' => 19],
            ['id' => 196, 'name' => 'Chinchipe', 'state_id' => 19],
            ['id' => 197, 'name' => 'Nangaritza', 'state_id' => 19],
            ['id' => 198, 'name' => 'Yacuambi', 'state_id' => 19],
            ['id' => 199, 'name' => 'Yantzaza (Yanzatza)', 'state_id' => 19],
            ['id' => 200, 'name' => 'El Pangui', 'state_id' => 19],
            ['id' => 201, 'name' => 'Centinela del Cóndor', 'state_id' => 19],
            ['id' => 202, 'name' => 'Palanda', 'state_id' => 19],
            ['id' => 203, 'name' => 'Paquisha', 'state_id' => 19],
            ['id' => 204, 'name' => 'San Cristóbal', 'state_id' => 20],
            ['id' => 205, 'name' => 'Isabela', 'state_id' => 20],
            ['id' => 206, 'name' => 'Santa Cruz', 'state_id' => 20],
            ['id' => 207, 'name' => 'Lago Agrio', 'state_id' => 21],
            ['id' => 208, 'name' => 'Gonzalo Pizarro', 'state_id' => 21],
            ['id' => 209, 'name' => 'Putumayo', 'state_id' => 21],
            ['id' => 210, 'name' => 'Shushufindi', 'state_id' => 21],
            ['id' => 211, 'name' => 'Sucumbíos', 'state_id' => 21],
            ['id' => 212, 'name' => 'Cascales', 'state_id' => 21],
            ['id' => 213, 'name' => 'Cuyabeno', 'state_id' => 21],
            ['id' => 214, 'name' => 'Orellana', 'state_id' => 22],
            ['id' => 215, 'name' => 'Aguarico', 'state_id' => 22],
            ['id' => 216, 'name' => 'La Joya de Los Sachas', 'state_id' => 22],
            ['id' => 217, 'name' => 'Loreto', 'state_id' => 22],
            ['id' => 218, 'name' => 'Santo Domingo', 'state_id' => 23],
            ['id' => 219, 'name' => 'Santa Elena', 'state_id' => 24],
            ['id' => 220, 'name' => 'La Libertad', 'state_id' => 24],
            ['id' => 221, 'name' => 'Salinas', 'state_id' => 24]
        ];
        City::insert($cityRecords);
    }
}
